modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Sqbika/AFarmK/issues"
license="GNU General Public License v3.0"

[[mods]]
modId="afarmk"
version="${file.jarVersion}"
displayName="AFarmK"
logoFile="afarmk.png"
authors="Sqbika"
description='''
If you are tired of holding a keybind, I'm here to help.
'''
